language: python
python:
  - "3.9"

before_install:
  - pip install codecov

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

after_success:
  - codecov # submit coverage
